default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: api-ruff
        name: API Ruff
        entry: uv run --locked --directory api ruff check .
        language: system
        pass_filenames: false
        files: ^(api/|\.pre-commit-config\.yaml$)

      - id: api-format
        name: API Ruff format
        entry: uv run --locked --directory api ruff format --check .
        language: system
        pass_filenames: false
        files: ^(api/|\.pre-commit-config\.yaml$)

      - id: api-mypy
        name: API MyPy
        entry: uv run --locked --directory api mypy .
        language: system
        pass_filenames: false
        files: ^(api/|\.pre-commit-config\.yaml$)

      - id: gpu-api-ruff
        name: GPU API Ruff
        entry: uv run --locked --directory gpu-api ruff check .
        language: system
        pass_filenames: false
        files: ^(gpu-api/|\.pre-commit-config\.yaml$)

      - id: gpu-api-format
        name: GPU API Ruff format
        entry: uv run --locked --directory gpu-api ruff format --check .
        language: system
        pass_filenames: false
        files: ^(gpu-api/|\.pre-commit-config\.yaml$)

      - id: gpu-api-mypy
        name: GPU API MyPy
        entry: uv run --locked --directory gpu-api mypy .
        language: system
        pass_filenames: false
        files: ^(gpu-api/|\.pre-commit-config\.yaml$)
