name: Docker (Web)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: finki-hub/.github/.github/workflows/docker.yaml@main
    with:
      dockerfile: ./web/Dockerfile
      context: ./web
      package-name: chat-bot-web
      cache-backend: registry
      build-args: |
        NEXT_DEPLOYMENT_ID=${{ github.sha }}
        NEXT_PUBLIC_POSTHOG_KEY=${{ vars.NEXT_PUBLIC_POSTHOG_KEY }}
    secrets: inherit
