name: Linters (API)

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    uses: ./.github/workflows/python-ruff.yaml
    with:
      working-directory: ./api

  mypy:
    uses: ./.github/workflows/python-mypy.yaml
    with:
      working-directory: ./api
