name: Tests (Web)

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vitest:
    uses: finki-hub/.github/.github/workflows/vitest.yaml@766c1cef1421fc3fe4794d9fc000f47e6d34d43d # main
    with:
      working-directory: ./web
